/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.1.1/samples
 */

import org.gradle.api.JavaVersion

plugins {
    // Apply the java plugin to add support for Java
    `java`
    // Apply the application plugin to add support for building an application
    `application`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

// use java 21 source and target compatibility
java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.8.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
}

